-- ('Akira class',),
INSERT INTO SHIP (ShipClass, ShipName, Registry, Depiction)
VALUES
('Akira class','Name', 'Registry', 'Depiction'),
('Akira class','USS Gryphon', 'NCC-65550', 'Commanded by Captain Elaine Mello. Assigned to defend Deep Space Nine for a short period of time after the Dominion War in the Deep Space Nine relaunch.[citation needed]'),
('Akira class','USS James T Kirk', 'NCC-91277', 'Commanded by Captain Elias Vaughn. Named in honor of the famous Starfleet captain. Destroyed in the defense of Federation worlds against the mass Borg Invasion of 2381, resulting in the death of 31 crew members and Captain Vaughn being left brain dead.'),
('Akira class','USS Rabin', 'NCC-63293', 'Participates in the Battle of Sector 001.[2]'),
('Akira class','USS Thunderchild', 'NCC-63549', 'Participates in the Battle of Sector 001 in 2373.[2]'),
('Akira class','USS Geronimo', 'NCC-69302', 'Commanded by Captain Gregory McCray; Major supporting ship in Star Trek: Bridge Commander.'),
('Akira class','USS Leyte Gulf', 'NCC-71427', 'Commanded by Captain Aaron Juraj; first Starfleet vessel to be infected by nanites in Star Trek: Away Team.'),
('Akira class','USS Dakota', 'NCC-63892', 'Participates in the Battle of Sector 001 in 2373.[2] Lost patrolling the border of the Cardassian Demilitarized Zone.[3]'),
('Akira class','USS Devore', 'NCC-64088', 'Commanded by Captain Joshua Martin; Supporting ship in Star Trek: Bridge Commander.'),
('Akira class','USS Delestrez', 'NCC-64013', 'Commanded by Captain Juliette; Supporting ship in Celestia Universe.'),
('Akira class','USS Summit', 'NCC-63546', 'Attempts to rescue the Enterprise-E on Gemworld. Destroyed by a dimensional rift immediately after dropping out of warp. Lost with all hands.[citation needed]'),
-- ('Ambassador class',),
('Ambassador class','Name', 'Registry', 'Depiction'),
('Ambassador class','USS Adelphi', 'NCC-26849', 'Crew made a botched first contact with the Ghorusda.[4]'),
('Ambassador class','USS Enterprise', 'NCC-1701-C', 'Commanded by Captain Rachel Garrett presumed to be Killed In Action when the ship was destroyed defending the Klingon outpost at Narendra III from Romulan attack.[5] Helmsman Richard Castillo assumed command of the Enterprise-C in 2366 and returned to the year 2344 where the ship was destroyed defending the Klingon outpost.'),
('Ambassador class','USS Excalibur', 'NCC-26517', 'Part of the tachyon blockade during the Klingon Civil War.[6] Mentioned as commanded by Captain Morgen, an old crewmate of Picard in the novel Reunion. Later commanded by Captain Mackenzie Calhoun in Star Trek: New Frontier. Destroyed during the New Frontier series and replaced with another starship with the name, with the new ship being a Galaxy class.'),
('Ambassador class','USS Exeter', 'NCC-26531', 'Tom Paris''s assignment before being dismissed from Starfleet.[7] Participated in the Dominion War.[8] Later commanded by Captain Elizabeth Shelby, followed by Captain Alexandra Garbeck in Star Trek: New Frontier.'),
('Ambassador class','USS Gandhi', 'NCC-26632', 'Ship to which Thomas Riker is assigned.[9][10]'),
('Ambassador class','USS Horatio', 'NCC-10532', 'Commanded by Captain Walker Keel.[11] Destroyed by agents of an alien conspiracy to take over Starfleet.[11]'),
('Ambassador class','USS Valdemar', 'NCC-26198', 'Sent to the border of the Cardassian Demilitarized Zone.[3]'),
('Ambassador class','USS Yamaguchi', 'NCC-26510', 'Destroyed by the Borg at the Battle of Wolf 359.[12]'),
('Ambassador class','USS Zhukov', 'NCC-26136', 'Made cultural observation of Alpha Laputa IV.[13] Previous assignment of Lt. Barclay before his transfer to the Enterprise-D[14] Supporting ship in Star Trek: Bridge Commander, commanded by an Andorian Captain Verata, the ship escorts the USS Sovereign to Starbase 12 and participates in several battles.'),
('Ambassador class','USS Loma Prieta', 'NCC-26848-A', 'Flagship of Admiral T’Nae during Sela''s assault on Vulcan in 2409.'),
-- ('Andromeda class', ),
-- ('Named for Greek mythological figure and nearby Andromeda Galaxy.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Andromeda class', 'USS Drake', 'NCC-70956', 'Ambushed by a Klingon battle squadron.[15]'),
('Andromeda class', 'USS Prokofiev', 'NCC-68814', 'Dispatched to the border of the Federation–Cardassian Demilitarized Zone.[3]'),
-- ('Antares class',),
-- ('Named for star Antares.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Antares class','USS Antares aka SS Antares', 'NCC-501', 'Rescued and is later destroyed by Charlie Evans.[16]'),
('Antares class','USS Hermes', 'NCC-10376', 'Part of the tachyon blockade during the Klingon Civil War.[6]'),
-- ('Apollo class',),
-- ('Named for the ancient Greek solar deity and the American Apollo program (NASA).'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Apollo class','USS Agamemnon', 'NCC-11638', 'Part of the tachyon blockade during the Klingon Civil War.[6] Part of "Task Force 3" sent to face an anticipated Borg attack.[17]'),
('Apollo class','USS Ajax', 'NCC-11574', 'Cortin Zweller''s first assignment.[18] Received experimental warp drive technology.[19] Part of the tachyon blockade during the Klingon Civil War.[6]'),
('Apollo class','USS Clement', 'NCC-12537', 'Scheduled to rendezvous with the Enterprise-D.[20]'),
('Apollo class','USS Gage', 'NCC-11672', 'Destroyed at the Battle of Wolf 359.[21]'),
-- ('Archer class',),
-- ('Scout ship introduced in the Star Trek: The Original Series tie-in novel series Star Trek: Vanguard and its follow-up Star Trek: Seekers. Retroactively named after Captain Jonathan Archer from Star Trek: Enterprise.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Archer class','USS Archer', 'NCC-44278', 'Presumable namesake ship for the class. Presumably named for Jonathan Archer.'),
('Archer class','USS Huang Zhong', 'NX-45298', 'Mentioned in the tie-in novel Star Trek: Seekers #4: All That''s Left. Crashed on a planet in a spatial rift. Crew rescued by the Enterprise resulting in first contact with the Dolysians.'),
('Archer class','USS Sagittarius', 'NCC-1894', 'Commanded by Clark Terrell prior to taking command of the USS Reliant. Assigned to explore the Taurus Reach. Presumably named for the constellation.'),
-- ('Bradbury class',),
-- ('Name honors science fiction author Ray Bradbury.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Bradbury class','USS Bradbury', 'NX-72307', 'Scheduled to transport Wesley Crusher to Starfleet Academy and undergoes warp drive performance tests.[22][23] In Star Trek Into Darkness, Spock was to be reassigned to another Bradbury following Kirk''s demotion from Captain of the Enterprise. In the end, he was reinstated to the Enterprise.[24]'),
-- (''),
-- (''),
-- ('Cardenas class',),
-- ('Named for United States Air Force brigadier general Robert Cardenas.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Cardenas class','USS Buran', 'NCC-1422', 'The ship was ambushed by Klingons about a month after the beginning of the 2256 Federation-Klingon war and apparently destroyed. Its captain at the time was Gabriel Lorca. At some point Lorca was replaced by his mirror-universe counterpart, who impersonated him and reported that ship was boarded, then set to self destruct by him so that its crew doesn''t fall into Klingon hands and face degradation, torture and slow public death.[25][26]'),
(''),
('Cardenas class','USS Yeager', 'NCC-1437', 'Destroyed at the Battle at the Binary Stars.'),
-- ('Centaur class',),
-- ('Name', 'Registry', 'Depiction'),
('Centaur class','USS Centaur', 'NCC-42043', 'Centaur class: kitbash of the Excelsior and Miranda models.[27]'),
-- ('Challenger class',),
-- ('Name', 'Registry', 'Depiction'),
('Challenger class','USS Armstrong', 'NCC-57537', 'Ambushed by a Klingon battle group. Name honors astronaut Neil Armstrong, commander of Apollo 11.'),
('Challenger class','USS Buran', 'NCC-57580', 'Destroyed at the Battle of Wolf 359.[21] Second ship to carry this name, after Cardenas-class NCC-1422.'),
('Challenger class','USS Kearsarge', 'NCC-57566', 'Rendezvoused with the Enterprise-D.[28]'),
-- ('Cheyenne class',),
-- ('Name', 'Registry', 'Depiction'),
('Cheyenne class','USS Ahwahnee', 'NCC-71620/NCC-73620', 'Heavily damaged at the Battle of Wolf 359.[21] Presumed repaired to participate in the tachyon blockade during the Klingon Civil War.[6]'),
-- ('Chimera class',),
-- ('Named for the mythical chimaera.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Chimera class','USS Portland', 'NCC-57418', 'Searches the Algira sector for Odo and Elim Garak when their runabout goes missing.[29]'),
-- ('Columbia class',),
-- ('Name', 'Registry', 'Depiction'),
('Columbia class','USS Endeavour', 'NCC-06', 'Originally the last active NX class starship in the Earth Starfleet. Transferred to Federation Starfleet service and rebuilt into the first Columbia class starship.'),
-- ('Constellation class',),
-- ('In the script of the TNG episode "The Battle," Geordi La Forge identified the Stargazer as a Constitution Class, but it was dubbed to Constellation after the script was changed.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Constellation class','USS Billings', 'NCC-3907', 'Kathryn Janeway''s first command.[30]'),
('Constellation class','USS Constellation', 'NCC-1974', ''),
('Constellation class','USS Gettysburg', 'NCC-3890', 'Under Captain Mark Jameson, rescued hostages from Mordan IV.[31] Served in the Dominion War.[32]'),
('Constellation class','USS Hathaway', 'NCC-2593', 'Decommissioned, participated in exercises against the USS Enterprise-D. Its destruction was faked in a ruse to foil Ferengi attackers. Named for the wife of William Shakespeare.[1][33]'),
('Constellation class','USS Magellan', 'NCC-3069', 'Referred to by Captain Sisko as one of the ships to protect the USS Defiant''s flank.[34]'),
('Constellation class','USS Stargazer', 'NCC-2893', 'Jean-Luc Picard''s first command.[35] Abandoned following the Battle of Maxia, later recovered by Starfleet.[35]'),
('Constellation class','USS Victory', 'NCC-9754', 'Ship on which Geordi La Forge once served.[36][37] Participated in the Dominion War.[38] Named after the Napoleonic Wars British Royal Navy flagship, HMS Victory flagship of Horatio Nelson, 1st Viscount Nelson.'),
-- ('Constitution class',),
-- ('Named for the USS Constitution. (The TOS USS Enterprise dedication plaque refers to this ship class as the "Starship Class".)'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Constitution class','USS Constellation', 'NCC-1017', 'Commanded by Commodore Matthew Decker. All of crew was killed by the Doomsday Machine except for Commodore Decker.[39] Used as a bomb to destroy the planet-killer.'),
('Constitution class','USS Constitution', 'NCC-1700', 'Lead ship of the class (previously NX-1700).'),
('Constitution class','USS Defiant', 'NCC-1764', 'The ship is lost in an interdimensional rift in "The Tholian Web".[40] Later, it is revealed she was taken by Mirror Universe Tholians, captured by the crew of the ISS Enterprise (NX-01), and then used in the service of the Terran Empire in "In a Mirror, Darkly".[41] In Star Trek Continues (episode 8, "Still Treads the Shadow"), Defiant is duplicated during its passage through the interdimensional rift into interphasic space with only a duplicate Kirk aboard. Over the next two hundred years, it gains a sentient AI who attempts to bring it back into the prime universe. The attempt has potentially disastrous consequences and is foiled by both Kirks, the duplicate returning to interphasic space. A Defiant is mentioned, but not seen (except for a wireframe graphic) in Star Trek Discovery, Season One. Oddly, though the Defiant appears in TOS, the Star Fleet Technical Manual lists no Defiant in any of the starship classes mentioned though the book was published seven years after the fact. However, there are several classes not listed in the publication. The Defiant is listed as a Bonhomme Richard subclass of the Constitution class. In the Star Fleet Technical Manual, it lists the registry number of "NCC-1764" as belonging to the Galina. Since the Defiant appears in an episode, and the Galina does not, then the Defiant is the sole owner of the NCC-1764. But, one possibility is, the number was attached to the Galina after the disappearance of the Defiant.'),
('Constitution class','ISS Enterprise', 'NCC-1701', 'Mirror Universe version of the USS Enterprise in "Mirror, Mirror".[42]'),
('Constitution class','USS Enterprise', 'NCC-1701', 'Commanded by Robert April (2245–2250), Christopher Pike (2250–2265), James T. Kirk (2265–2270, 2273–2280, 2285), Willard Decker (2270–2273, ship''s commander during refit up to V''Ger incident), and Spock (2280–2285, at which time Enterprise was assigned to Starfleet Academy as a training ship). Vessel''s self-destruction carried out while in orbit of the Genesis planet to prevent ship from falling into Klingon hands.[43]'),
('Constitution class','USS Enterprise (Kelvin Timeline)', 'NCC-1701', 'Originally commanded by Christopher Pike (launched 2258), then James T. Kirk.[44] Destroyed by Krall in 2263.[45]'),
('Constitution class','USS Excalibur', 'NCC-1664[1]', 'Severely damaged and crew killed during Richard Daystrom''s M5 computer test.[46] In TOS episode "The Ultimate Computer", the death of its entire crew is established, however, the status of the Excalibur itself is unclear. It is not determined whether the ship was destroyed or severely damaged. The Star Trek Chronology (2nd ed., p. 88) stated that the ship was destroyed. The fourth edition of the Star Trek Encyclopedia offered two possibilities of the conditions of the Excalibur – the ship was severely damaged in (vol. 1, p. 254) or accidentally destroyed in (vol. 2, p. 329). Even though the episode itself provided no firm confirmation either way. The 1973 Franz Joseph Blueprints list this ship as NCC-1705.'),
('Constitution class','USS Exeter', 'NCC-1672[1]', 'All crew lost (killed by alien disease) except for Captain Ronald Tracey, who was on the planet''s surface when the disease struck his crew.[47] At the end of the series Captain James T. Kirk stated that the Exeter was an abandoned ship, being infected with the virus of Omega IV. Best estimates were that the Exeter was destroyed to keep the infection from spreading throughout the galaxy. See USS Kongo for its ultimate fate. The 1973 Franz Joseph Blueprints list this ship as NCC-1706.'),
('Constitution class','USS Farragut', 'NCC-1647[1]', 'Ship on which James Kirk served as a phaser station operator.[48] Attacked by the dikironium cloud creature, which killed half the crew.[48] The ship never appeared on screen and was never given a class or registry number; both come from The Star Trek Encyclopedia.[1] The 1973 Franz Joseph Blueprints list this ship as NCC-1702.'),
('Constitution class','USS Hood', 'NCC-1703[1]', 'Participates in Richard Daystrom''s M5 computer test.[46] Destroyed by sabotage in Star Trek Continues episode 7, "Embracing the Winds". In episodes 10–11 "To Boldly Go", we find out this was done by espers. The 1973 Franz Joseph Blueprints list this ship as NCC-1707.'),
('Constitution class','USS Intrepid', 'NCC-1631[1]', 'All-Vulcan crew destroyed by a massive, spacegoing single-celled life form.[49] The 1973 Franz Joseph Blueprints list this ship as NCC-1708.'),
('Constitution class','USS Kongo', 'NCC-1710', 'In Star Trek Continues episodes 10–11 "To Boldly Go", the Kongo is hijacked by espers and taken to the galactic barrier. They then head for Earth with murderous intent. With the help of Romulan commander Charvanek and her Hawk''s Talon, the Enterprise foils them, but not before they trick the Exeter and Potemkin into destroying each other. In their last act of defiance, the espers destroy the Kongo.'),
('Constitution class','USS Lexington', 'NCC-1709[1]', 'Participates in Richard Daystrom''s M5 computer test. Commanded by Commodore Robert Wesley.[46] The 1973 Franz Joseph Blueprints list this ship as NCC-1703.'),
('Constitution class','USS Pegasus', 'NCC-1702', 'Patrolled the Klingon Neutral Zone.[50]'),
('Constitution class','USS Potemkin', 'NCC-1657[1]', 'Participates in Richard Daystrom''s M5 computer test.[46] See USS Kongo for its ultimate fate. The 1973 Franz Joseph Blueprints list this ship as NCC-1711.'),
('Constitution class','USS Republic', 'NCC-1371', 'Although many reference sources included Republic as a Constitution-class heavy cruiser, its status in canon is, to date, uncertain. Kirk himself stated in the episode "Court Martial" the ship''s nomenclature as "United Starship Republic, number 1371".'),
('Constitution class','USS Valiant', 'NCC-1623', 'For his influential "The Case of Jonathan Doe Starship" article, published in the April 1973 issue 27 of the T-Negative fanzine, future Star Trek model maker Greg Jein accepted the producer''s intent and endowed Valiant with the appropriately lower conjectural registry number NCC-1623. But unlike many of his other conjectural Constitution-class registry numbers, the 2006 remastered version of the series afforded no opportunity to bring this ship to canon. The reference book Star Fleet Technical Manual also listed a Constitution-class starship with the name Valiant but assigned with the registry NCC-1709. The 1973 Franz Joseph Blueprints list this ship as NCC-1709 also.'),
('Constitution class','USS Yorktown', 'NCC-1717', 'Disabled by alien probe.[51] The 1973 Franz Joseph Blueprints list this ship as NCC-1704.'),
-- ('Constitution class refit',),
-- ('Ostensibly a refit of the Constitution class, this ship is referred to as "Enterprise class" in Andrew G. Probert''s non-canon Star Trek The Motion Picture: 14 Official Blueprints.[52][53]'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Constitution class refit','USS Enterprise', 'NCC-1701', 'USS Enterprise NCC-1701 was refitted following extensive service.[51] with upgraded weapons, shields, sensors, and warp core. Commanded during refit by Captain Willard Decker. Command given to Admiral James T. Kirk after he met with Starfleet Command.[51] Spock handed control over to Kirk.[54] Eventually stolen and destroyed while in orbit of the Genesis planet to prevent it from falling into Klingon hands.[55] Served as primary vessel for Star Trek: The Motion Picture, Star Trek II: The Wrath of Khan, and Star Trek III: The Search for Spock.'),
('Constitution class refit','USS Yorktown', 'NCC 1717', ''),
('Constitution class refit','USS Enterprise', 'NCC 1701 A (from 2286)', 'Disabled by whale probe, then possibly salvaged and renamed Enterprise; although no onscreen evidence supports this. Command given to James T. Kirk following his demotion to Captain.[56] Primary setting for Star Trek V: The Final Frontier and Star Trek VI: The Undiscovered Country, later decommissioned.[50]'),
('Constitution class refit','USS Constitution', 'NCC-1700', 'Destroyed at the Battle of Wolf 359, wreckage discovered by crew of Enterprise-D.'),
('Constitution class refit','USS Explorer', 'NCC-1986', 'Seen investigating the results of the Tabula Rasa Incident in the opening sequence of the video game Star Trek: New Worlds. Commanded by Captain Gibson.'),
('Constitution class refit','USS Kongo', 'NCC-1710', 'The refit Kongo NCC-1710 was put into active service just after the V''Ger crisis of 2268. According to the unseen page 4 of the "Operation Retrieve" briefing charts, the Kongo was commanded by N. Rodis, and the ship was located in Sector 21803 in the year 2293. The ship''s captain was named after the sixth movie''s art director Nilo Rodis-Jamero.'),
('Constitution class refit','USS Ranger', 'NCC-1707', 'Another simulated Enterprise class ship used by Starfleet Academy trainees in Star Trek: Starfleet Academy. (Simulation ship)'),
('Constitution class refit','USS Paris', 'NCC-1804', 'Destroyed in The Battle of Caleb IV.'),
-- ('Crossfield class',),
-- ('Named for American naval officer and test pilot Albert Scott Crossfield who became the first human to fly at twice the speed of sound.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Crossfield class','USS Discovery', 'NCC-1031', 'Titular ship in 2017 television series Star Trek: Discovery. Initially commanded by Captain Gabriel Lorca, and later by Captain Christopher Pike, the Discovery is a science vessel commissioned to investigate potential forms of faster-than-light propulsion such as the spore drive.'),
('Crossfield class','USS Glenn', 'NCC-1030', 'Sister ship to the Discovery. Scuttled following a failed propulsion experiment.[57]'),
('Crossfield class','USS Crossfield', 'NCC-1029', 'Presumable namesake ship for the class.'),
-- ('Daedalus class',),
-- ('Named for an iconic figure from Greek mythology.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Daedalus class','USS Archon', 'NCC-189[1]', 'Destroyed by an alien computer in 2167 near Beta III.[58]'),
('Daedalus class','USS Carolina', 'NCC-160[1]', 'Freighter.[59]'),
('Daedalus class','USS Essex', 'NCC-173', 'Damaged and crashed on Mab-Bu VI.[60]'),
('Daedalus class','USS Horizon', 'NCC-176', 'A model of this ship was on display in the school aboard Deep Space 9 in early 2369. (DS9: "The Nagus").'),
('Daedalus class','USS Pilgrim', 'NCC-178', 'Active in the year 2159 in the vicinity of one of Starfleet''s first starbases. Appears in the Star Trek videogame "Legacy".'),
('Daedalus class','USS Lovell', 'NCC-470', 'Dedicated vessel of the Starfleet Corps of Engineers. Appears in the novel series Star Trek: Vanguard. Likely named after Capt. James Lovell, USN, Gemini and Apollo astronaut.'),
('Daedalus class','USS Masao', 'unknown', 'Dedicated vessel of the Starfleet Corps of Engineers. Mentioned in the tie-in novel Star Trek: Seekers #4: All That''s Left.'),
('Daedalus class','USS Zander', 'unknown', 'Dedicated vessel of the Starfleet Corps of Engineers. Mentioned in the tie-in novel Star Trek: Seekers #4: All That''s Left.'),
-- ('Defiant class',),
-- ('Name', 'Registry', 'Depiction'),
('Defiant class','USS Defiant', 'NX-74205', 'Pathfinder. Assigned to space station Deep Space Nine.[61] Participates in the Battle of Sector 001.[2] Destroyed at the Second Battle of Chin''toka.[62]'),
('Defiant class','USS Defiant', '(dedication plaque) NCC-75633 (exterior) NX-74205', 'Formerly the USS São Paulo.[63] Assigned to space station Deep Space Nine.[63] Participates in the Battle of Cardassia.[64]'),
('Defiant class','USS Saladin', 'NCC-74350', 'Commanded by Captain Shinoda during the Dominion War in the short story "Safe Harbors".'),
('Defiant class','USS Valiant', 'NCC-74210', 'Starfleet Academy Red Squad training ship. The vessel gets caught behind enemy lines after the outbreak of the Dominion War, suffered heavy losses among the standard crew and was subsequently commanded by the cadets of Red Squad. Destroyed by the Jem''Hadar after a failed attempt to destroy a new Dominion vessel. Only three people survived the destruction of the ship, (Jake Sisko, Nog, and Collins, a member of Red Squad).[65]'),
('Defiant class','USS Monitor', 'NCC-75001', 'Mentioned in both the books The Return and Preserver, lost under command of Captain John Scott Lewinski attempting to set a new warp speed record with recovered Borg transwarp drive.'),
('Defiant class','USS Eagle', 'Unknown', 'Star Trek Voyager One of two Defiant class ships assigned to either recover or destroy the NX Prometheus after it was captured by Romulans. Was accidentally fired upon by the EMHs from the USS Voyager and the NX Prometheus.'),
('Defiant class','USS Nirvana', 'Unknown', 'Star Trek Voyager One of two Defiant class ships assigned to either recover or destroy the NX Prometheus after it was captured by Romulans.'),
-- ('Deneva class',),
-- ('Named for the fictional planet in the TOS episode "Operation: Annihilate!".'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Deneva class','USS Arcos', 'NCC-6237', 'Destroyed by a warp core breach near Turkana IV in 2367. Crew evacuates to the planet''s surface and is rescued by the Enterprise-D.[66]'),
('Deneva class','USS LaSalle', 'NCC-6203', 'Reports unusual radiation anomalies in the Gamma Arigulon system.[67]'),
-- ('Dreadnought class',),
-- ('Name', 'Registry', 'Depiction'),
('Dreadnought class','USS Vengeance', 'NCC-177358', 'Developed by Starfleet Admiral Alexander Marcus of Section 31 to combat the Klingon Empire.'),
-- ('Einstein class'),
-- ('Named for Albert Einstein'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Einstein class', 'USS Kelvin', 'NCC-0514', 'In the timeline at the start of the movie Star Trek, the Kelvin was in service with Starfleet in the early 23rd century. In 2233, the Kelvin was under the command of Captain Richard Robau; his first officer was Lieutenant Commander George Kirk. Kirk''s wife, Winona, was also aboard the ship at that time while she was pregnant with their son, James T. Kirk. The Kelvin was destroyed by the Romulan mining ship Narada, which arrived from the distant future through an artificial black hole.[44] Named for director J. J. Abrams'' grandfather.[68] Its registry number, NCC-0514, comes from Abrams''s birthdate of May 14.'),
-- ('Engle class',),
-- ('Named for American test pilot and astronaut Joe Engle who test-flew the joint NASA–Air Force North American X-15 rocket airplane and the space shuttle Enterprise before eventually commanding the space shuttle Columbia.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Engle class','USS Earhart', 'NCC-1052', 'Fought at the Battle at the Binary Stars.'),
('Engle class','USS T''Plana-Hath', 'NCC-1004', 'Destroyed at the Battle at the Binary Stars.'),
-- ('Erewhon class',),
-- ('Name', 'Registry', 'Depiction'),
('Erewhon class','SS Santa Maria', 'NCC-529', 'Personnel Transport about 4 times the size of the Runabout. Cannibalised for parts and for use as a shelter by human settlers in a colony that rejects technology.[69]'),
-- ('Excelsior class', ),
-- ('This fictional spacecraft design was introduced to the Star Trek sci-fi universe in 1984.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Excelsior class', 'USS Al-Batani', 'NCC-42995', 'Although it never appeared on screen, the Al-Batani is mentioned in dialogue as the first ship aboard which Kathryn Janeway served, which at the time was captained by Tom Paris'' father Owen Paris.[70][71] Never defined on screen, the class and registry number come from the non-canon Star Trek Encyclopedia.[1]'),
('Excelsior class', 'USS Berlin', 'NCC-14232', 'Patrolled the Romulan Neutral Zone.[72]'),
('Excelsior class', 'USS Cairo', 'NCC-42136', 'Transfers Captain Edward Jellico to the Enterprise-D.[73]'),
('Excelsior class', 'USS Charleston', 'NCC-42285', 'Transported three previously cryogenically frozen people to Earth.[74] Part of the tachyon blockade during the Klingon Civil War.[6]'),
('Excelsior class', 'USS Crazy Horse', 'NCC-50446', 'Part of Task Force 3 sent to face an anticipated Borg invasion.[17] Set to rendezvous with the Enterprise-D to transfer Rear Admiral Erik Pressman.[75]'),
('Excelsior class', 'USS Crockett', 'NCC-38955', 'Transported Admiral Mitsuya to Deep Space Nine.[69]'),
('Excelsior class', 'USS Dallas', 'NCC-2019', 'Dedication plaque states "Last starship of her class".[76]'),
('Excelsior class', 'USS Enterprise', 'NCC-1701-B', 'Ship aboard which James T. Kirk is lost and presumed dead. First commanded by Captain Jon Harriman.[77]'),
('Excelsior class', 'USS Excelsior', 'NCC-2000, previously NX-2000', 'Pathfinder and transwarp drive testbed.[43] In The Search for Spock, the ship was dubbed "the great experiment" and was days away from its first test run. It was unexpectedly called into service to stop Admiral Kirk and his crew from stealing the soon to be decommissioned Enterprise. Attempting to use the transwarp drive to bring the ship back to spacedock, the Excelsior was sabotaged by Montgomery Scott and was left inoperable. Following the embarrassing failure, the Excelsior underwent repairs in spacedock before its recommission into active duty. Fails in attempt to rescue Captain James T. Kirk and Dr. Leonard McCoy from Qo''noS.[78] Helps defeat General Chang over Khitomer.[50] Ship aboard which Tuvok serves as science officer.[78] Commanded by Captain Styles in Star Trek III: The Search for Spock and Captain Hikaru Sulu in Star Trek VI: The Undiscovered Country.'),
('Excelsior class', 'USS Farragut', 'NCC-2021', 'Transported several genetically enhanced humans to Deep Space Nine.[79][80]'),
('Excelsior class', 'USS Fearless', 'NCC-14598', 'Assigned to planetary mapping in the Beta Mahoga system.[23] Received new warp technology.[19] Briefly seen in The Next Generation episode "Where No One Has Gone Before"'),
('Excelsior class', 'USS Fredrickson', 'NCC-42111', 'Briefly at Utopia Planitia Fleet Yards.[81] Serves in the Dominion War.[27]'),
('Excelsior class', 'USS Gorkon', 'NCC-40512', 'Sent to face a possible Borg invasion.[17]'),
('Excelsior class', 'USS Grissom', 'NCC-42857', 'Assists the Enterprise-D during a contamination problem on Beta Agni II. Name pays tribute to astronaut Gus Grissom, commander of Apollo 1.[82] Destroyed at the Battle of Ricktor Prime.[83]'),
('Excelsior class', 'USS Hood', 'NCC-42296', 'William Riker''s assignment before his transfer to the USS Enterprise-D.[84] Part of the tachyon blockade during the Klingon Civil War.[6] Participates in the Battle for Deep Space 9[85] and First Battle of Chin''toka.[86] Part of Battle Group Omega sent to intercept Reman warship Scimitar.[87]'),
('Excelsior class', 'USS Intrepid', 'NCC-38907', 'Captained by Drew Dieghan. Responded to a Klingon distress call from the Khitomer outpost following a Romulan attack.[88]'),
('Excelsior class', 'USS Kongo', 'NCC-42173', 'The 2nd starship to bear the name Kongo NCC-42173 was a Excelsior Class Starship and was put in to service on Stardate: 2/2812 in the year 2343. The Kongo served with distinction up until late 2371, and was under the command of Captain William JL and First Officer Donavon. The Changeling invasion scare on Earth in 2372 forced Starfleet to activate some of there New Starship Programs in to service. The New Specifications of the Lakota Refit Configuration was add it to the Kongo Excelsior Class in year 2373. The Kongo after it''s Refit was under the New Command Of Captain Donavon in the year 2374. The Plaque reads as follows ("Never give up, Never Surrender").'),
('Excelsior class', 'USS Lakota', 'NCC-42768', 'Commanded by Captain Erika Benteen. Attempts to stop USS Defiant from reaching Earth under the orders of the rogue Admiral James Leyton.[89]'),
('Excelsior class', 'USS Malinche', 'NCC-38997', 'Commanded by Captain George Sanders. Patrolled the Cardassian border before the Dominion War. Severely damaged by the Maquis led by Michael Eddington.[90] Destroyed in 2381 during the Borg Invasion.'),
('Excelsior class', 'USS Melbourne', 'NCC-62043', 'Offered to William Riker to command.[21] Starfleet flagship at the Battle of Wolf 359, where it is destroyed.[21]'),
('Excelsior class', 'USS Okinawa', 'NCC-13958', 'Ship commanded by Admiral James Leyton and on which Benjamin Sisko served as first officer.[1][91]'),
('Excelsior class', 'USS Paris (Simulation ship)', 'NCC-2008', 'Simulated Excelsior class vessel used by Academy trainees in Star Trek: Starfleet Academy.'),
('Excelsior class', 'USS Repulse', 'NCC-2544', 'Katherine Pulaski''s assignment before the USS Enterprise-D.[92] Served in the Dominion War.[38]'),
('Excelsior class', 'USS Roosevelt', 'NCC-2573', 'Destroyed at the Battle of Wolf 359.[21][93]'),
('Excelsior class', 'USS Righteous', 'NCC-42451', 'Believed to have been vaporized by the Borg in 2366, in reality the ship was brought ten years into the future by Q in order to save it from destruction during the Battle of Wolf 359. Under the command of Captain Nikolai Andropov in Star Trek: Borg.'),
('Excelsior class', 'USS Valley Forge', 'NCC-43305', 'Damaged by an orbital defense platform at the Battle of Chin''toka.[86]'),
-- ('Freedom class',),
-- ('The name may have been supposed to honor the space station that was later simply called ISS.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Freedom class','USS Concorde', 'NCC-68711', 'Assigned near the Romulan Neutral Zone in an alternate timeline.[94]'),
('Freedom class','USS Firebrand', 'NCC-68723', 'Destroyed at the Battle of Wolf 359.[21]'),
('Freedom class','USS Mesquite', 'NCC-1789', 'Training ship, assigned to Starbase 1. Mentioned in Star Trek: Tactical Assault.'),
-- ('Galaxy class',),
-- ('Name', 'Registry', 'Depiction'),
('Galaxy class','USS Challenger', 'NCC-71099', 'Witnesses the return of USS Voyager to Earth.[95] Commanded by Captain Geordi La Forge in an alternate future.[96]'),
('Galaxy class','USS Cortez', 'NCC-78012', 'Referred to by Chief O''Brien and Captain Sisko during the mission to retake DS9.[97] Lost patrolling Cardassian border[98]'),
('Galaxy class','USS Dauntless', 'NCC-71879', 'First ship under players'' command in Star Trek: Bridge Commander. Destroyed while escorting a transport by Cardassian ships.'),
('Galaxy class','USS Enterprise', 'NCC-1701-D', 'Primary setting for Star Trek: The Next Generation. Captained by Jean-Luc Picard. Launched in 2363. Destroyed in 2371. Engineering section destroyed by warp core breach at Veridian III. Saucer section crash landed on Veridian III and rendered unsalvageable.[77]'),
('Galaxy class','USS Excalibur', 'NCC-26517-A', 'Commanded by Captain Mackenzie Calhoun, primary setting for the latter part of Star Trek: New Frontier as successor to the Ambassador class ship of the same name.'),
('Galaxy class','USS Galaxy', 'NCC-70637 (NX-70637)', 'Pathfinder. Participates in the Battle for Deep Space 9,[85] First Battle of Chin''toka,[86] and Battle of Cardassia.[64] Part of Battle Group Omega sent to intercept Reman warship Scimitar.[87]'),
('Galaxy class','USS London', 'NCC-2012-C', 'Participates in the Battle for Deep Space 9.[85]'),
('Galaxy class','USS Musashi', 'NCC-71809', 'Mentioned in the conversation of log transcription for Graviton Stabilizer by Ensign Nog.[32]'),
('Galaxy class','USS Odyssey', 'NCC-71832', 'Sent to rescue Benjamin Sisko from the Jem''Hadar. Destroyed in the rescue attempt.[99]'),
('Galaxy class','USS Robinson', 'NCC-71842', 'Taken command of by Benjamin Sisko after the Borg Invasion of 2381 in the novel Star Trek: Typhon Pact – Rough Beasts of Empire.'),
('Galaxy class','USS San Francisco', 'NCC-69480', 'Minor supporting vessel in Star Trek: Bridge Commander. Fate uncertain.'),
('Galaxy class','USS Sarek', 'NCC-72075', 'Replaced USS Cortez in formation during operation to retake DS9.[34]'),
('Galaxy class','USS Trident', 'NCC-31347', 'Commanded by Captain Elizabeth Shelby and later by Captain Kat Mueller in Star Trek: New Frontier.'),
('Galaxy class','USS Trinculo', 'NCC-71867', 'Part of the Starfleet Armada tasked with retaking Deep Space 9 from Dominion control during "Operation Return" (DS:9 episode "Sacrifice of Angels")'),
('Galaxy class','USS Venture', 'NCC-71854', 'Part of a Starfleet task force at Deep Space Nine during the Klingon invasion of the Cardassian Union.[100] Participates in the Battle for Deep Space 9[34][85] and the First Battle of Chin''toka.[86]'),
('Galaxy class','USS Yamato', 'NCC-71807 or NCC-1305-E[101]', 'Crew discovered Iconian artifacts but is infected by a computer virus that causes antimatter containment loss.[102] The virus causes the ship to explode with all hands lost. Commanded by Captain Donald Varley.'),
-- ('Galen class',),
-- ('Name', 'Registry', 'Depiction'),
('Galen class','USS Galen', 'NX-86350', 'Prototype, commanded by Commander Clarissa Glenn. Part of the Project Full Circle in the Star Trek: Voyager relaunch novels.'),
('Hokule‘a class',),
-- ('Presumably named for the Polynesian waʻa kaulua replica'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Hokule‘a class','USS Tripoli', 'NCC-19386', 'Discovered by Data.[103] Later assigned to Qualor II.[104]'),
-- ('Hoover class',),
-- ('Named for United States Air Force fighter pilot Bob Hoover who revolutionized modern aerobatic flying and in many aviation circles has been described as one of the greatest pilots ever to have lived.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Hoover class','USS Dana', 'NCC-1690', 'Fought at the Battle at the Binary Stars.'),
('Hoover class','USS Edison', 'NCC-1683', 'Destroyed at the Battle at the Binary Stars.'),
-- ('Intrepid class',),
-- ('Name', 'Registry', 'Depiction'),
('Intrepid class','USS Liberty', 'NX-74010', 'Part of Battle Group Omega sent to intercept Reman warship Scimitar.[87] Commanded by Captain Carl S. Bouchillon.'),
('Intrepid class','USS Pathfinder', 'NCC-74562', 'Captain Christine McDonald''s new command in the book Star Trek: Preserver. Destroyed in battle with USS Enterprise (NCC-1701-E) and Ferengi Marauder-class starship Leveraged Buyout around planet Halkan.'),
('Intrepid class','USS Intrepid', 'NCC-74600', 'Pathfinder vessel. Part of Battle Group Omega sent to intercept Reman warship Scimitar.[87]'),
('Intrepid class','USS Voyager', 'NCC-74656', 'Primary setting of Star Trek: Voyager where it is commanded by Captain Kathryn Janeway. Commanded by Captain Chakotay in the "Enemy of My Enemy" book series, then commanded by Captain Afsarah Eden in the novel Unworthy, then by Captain Chakotay as final commander in the novels Full Circle and Children of the Storm.'),
('Intrepid class','USS Bellerophon', 'NCC-74705', 'Transports Federation personnel to a summit on Romulus.[105] Flagship of Vice Admiral Ross during parts of the Dominion War.'),
('Intrepid class','USS Sally Ride', 'NCC-74710', 'Designed for deep space exploration and scientific discovery. It is the third ship in the Intrepid-class, having been commissioned at the same time as the USS Voyager. It has a cruising speed of warp 6 and a maximum sustainable speed of warp 9.975. Its armaments include ablative armor and quantum torpedoes. Commanded by Capt. Rafael Martinez. It appears in the Geek & Sundry web show Shield of Tomorrow.'),
-- ('Istanbul class',),
-- ('Named for the most populous city in Turkey.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Istanbul class','USS Constantinople', 'NCC-34852', 'Suffered a hull breach transporting colonists to Gravesworld.[106]'),
('Istanbul class','USS Havana', 'NCC-34043', 'Scheduled to rendezvous with the Enterprise-D in 2369.[107]'),
('Istanbul class','USS Sarajevo', 'NCC-38529', 'Lost in the Gamma Quadrant in 2371.[108] Later recovered and served in the Dominion War.[38]'),
-- ('Korolev class',),
-- ('Named for spacecraft designer Sergey Korolyov.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Korolev class','USS Goddard', 'NCC-59621', 'Delayed rendezvous with the Enterprise-D after the Acamarian Truce''s signing.[109] Part of the tachyon blockade during the Klingon Civil War.[6]'),
('Korolev class','USS Korolev', 'NCC-1650', 'Presumable namesake ship for the class.'),
-- ('Luna class',),
-- ('Featured in the Star Trek: Titan novels. All known Luna-class starships were named after moons in the Sol System.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Luna class','USS Luna', 'NX-80101', 'The prototype for the Luna-class. The ship was destroyed by a catastrophic engine failure before the events described in the novel Taking Wing of the Star Trek: Titan novel series took place.'),
('Luna class','USS Titan', 'NCC-80102', 'The USS Titan is the first command of Captain William Thomas Riker, former first officer of the USS Enterprise-D and USS Enterprise-E.[87] A Luna-class starship, designed primarily for scientific discovery. Described as 450 meters long, the Titan was built with state-of-the-art science facilities as opposed to being a more tactically pronounced starship. With a complement of about 350 persons, the USS Titan comprises the most racially diverse crew in Starfleet, with less than 15% of the population being human, as well as a number of non-humanoid beings. A full set of schematics of the USS Titan is available in the novel Sword of Damocles of the Star Trek: Titan novel series.'),
('Luna class','USS Oberon', 'NCC-80103', ''),
('Luna class','USS Europa', 'NCC-80104', ''),
('Luna class','USS Io', 'NCC-80105', ''),
('Luna class','USS Triton', 'NCC-80106', ''),
('Luna class','USS Ganymede', 'NCC-80107', ''),
('Luna class','USS Amalthea', 'NCC-80108', ''),
('Luna class','USS Callisto', 'NCC-80109', 'Captained by Admiral Trenton Cole, a long time friend of Picard''s.'),
('Luna class','USS Rhea', 'NCC-80110', 'Captained by Captain Bazel, a Saurian.'),
('Luna class','USS Charon', 'NCC-80111', 'Captained by Bellatora Fortis and destroyed during the novel Sword of Damocles of the Star Trek: Titan novel series.'),
('Luna class','USS Galatea', 'NCC-80112', ''),
('Luna class','USS Krakatoa', 'NCC-80115', 'Captained by Bartholomew Stavisky, a long time friend of Benjamin Sisko. Last command was USS Illinois NCC-12512, States class.'),
-- ('Magee class',),
-- ('Named for Royal Canadian Air Force fighter pilot and poet John Gillespie Magee Jr.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Magee class','USS Shran', 'NCC-1413', 'Destroyed at the Battle at the Binary Stars.'),
-- ('Malachowski class',),
-- ('Named for United States Air Force pilot Nicole Malachowski who became the first female member of the United States Air Force Thunderbirds.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Malachowski class','USS Clarke', 'NCC-1661', 'Destroyed at the Battle at the Binary Stars.'),
('Malachowski class','USS Sioux', 'NCC-1621', 'Fought at the Battle at the Binary Stars.'),
-- ('Mediterranean class',),
-- ('Name', 'Registry', 'Depiction'),
('Mediterranean class','USS Lalo', 'NCC-43837', 'Reports a "hiccup" in time that resulted from Dr. Paul Manheim''s experiments.[110] Destroyed by the Borg.[111]'),
('Mediterranean class','USS Wyoming', 'NCC-43730', 'Ship on which Tuvok served.[78]'),
-- ('Merced class',),
-- ('Name', 'Registry', 'Depiction'),
('Merced class','USS Merced', 'NCC-37120', 'Presumable namesake ship for the class.'),
('Merced class','USS Trieste', 'NCC-37124', 'Fell through a wormhole during Data''s tour of duty.[112] Stationed near Starbase 74 when the Enterprise-D is hijacked by the Bynars.[113]'),
-- ('Merian class',),
-- ('Name', 'Registry', 'Depiction'),
('Merian class','USS Curie', 'NCC-81890', 'Commanded by Captain Xin Chan. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle.'),
('Merian class','USS Hawking', 'NCC-81897', 'Commanded by Captain Bal Itak. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle.'),
('Merian class','USS Merian', 'Unknown', 'Presumable namesake ship for the class.'),
('Merian class','USS Planck', 'NCC-81894', 'Commanded by Captain Hosc T''Mar. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle.'),
-- ('Miranda class',),
-- ('Named for the character in the play The Tempest by William Shakespeare. Also the name of a moon.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Miranda class','USS Aephas', 'unknown', 'Featured in the tie-in novel Star Trek: Seekers #4: All That''s Left.'),
('Miranda class','USS Brittain', 'NCC-21166', 'Crew went insane due to loss of REM sleep.[114]'),
('Miranda class','USS Helin', 'NCC-1692', 'Patrolled the Romulan Neutral Zone.[50]'),
('Miranda class','USS Lantree', 'NCC-1837', 'Crew died after exposure to genetically engineered humans. Destroyed by the USS Enterprise-D.[92]'),
('Miranda class','USS Majestic', 'NCC-31060', 'Destroyed at the Battle for Deep Space 9.[85]'),
('Miranda class','USS Nautilus', 'NCC-31910', 'Participates in the First Battle of Chin''toka.[86]'),
('Miranda class','USS Reliant', 'NCC-1864', 'Ship on which Pavel Chekov serves as first officer.[115] Assigned to Project Genesis and later hijacked by Khan Noonien Singh.[115] Heavily damaged by USS Enterprise (NCC-1701), then destroyed by Genesis Device detonation.[115]'),
('Miranda class','USS Saratoga', 'NCC-1887', 'Disabled by the Whale Probe.[51]'),
('Miranda class','USS Saratoga', 'NCC-31911', 'Ship aboard which Benjamin Sisko served as first officer.[12] Destroyed at the Battle of Wolf 359.[12]'),
('Miranda class','USS Saratoga', 'NCC-31911-A', 'Replaced previous Saratoga; little else known.[citation needed]'),
('Miranda class','USS ShirKahr', 'NCC-31905', 'Destroyed in the First Battle of Chin''toka.[86]'),
('Miranda class','USS Sitak', 'NCC-1924', 'Destroyed at the Battle for Deep Space 9.[85]'),
('Miranda class','USS Tempest (simulation ship)', 'NCC-1852', 'Simulated Miranda class vessel used by Academy trainees in Star Trek: Starfleet Academy.'),
('Miranda class','USS Tiananmen', 'NCC-21382', 'Part of the tachyon blockade during the Klingon Civil War.[6] Went MIA while patrolling the Cardassian border during the Dominion War.[116] Participates at the First Battle of Chin''toka.[86] Named for the Tiananmen Square protests of 1989.[117]'),
('Miranda class','USS Trial', 'NCC-1948', 'Part of a Starfleet task force at Deep Space Nine during the Klingon invasion of the Cardassian Union.[100] Participates in the Battle for Deep Space 9.[85]'),
('Miranda class','USS Samuel B. Roberts', 'NCC-2020', 'Part of the Starfleet task force during the final battle of the Dominion war.[64] It was brought out of mothball status just two months before the final battle after having been extensively updated. It was badly damaged in the battle but survived. It was later decommissioned again and then scrapped after being deemed too far damaged to repair and mothball again.'),
('Miranda class','USS Lynx', 'NCC-78056', 'The Lynx was a troop transport during the Third Klingon And Federation War. She was later destroyed in a skirmish with a couple of Klingon Birds Of Prey, with all hands lost.'),
-- ('Mulciber class',),
-- ('Name', 'Registry', 'Depiction'),
('Mulciber class','USS Achilles', 'NCC-77024', 'Commanded by Captain Tillum Drafar. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle.'),
-- ('Nebula class',),
-- ('Name (in universe) denotes astronomical phenomenon and (real world) pays tribute to the Nebula Award for science fiction writing.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Nebula class','USS Bellerephon', 'NCC-62048', 'Destroyed at the Battle of Wolf 359.[12]'),
('Nebula class','USS Melbourne', 'NCC-62043', 'Destroyed at the Battle of Wolf 359. Remains of ship visible in aftermath of the battle in Star Trek: The Next Generation episode "The Best of Both Worlds, Part 2". Registry and name same as Excelsior class ship seen in Star Trek: Deep Space Nine pilot episode "Emissary".[118]'),
('Nebula class','USS Bonchune', 'NCC-70915', 'Sent to recover the USS Prometheus.[119]'),
('Nebula class','USS Endeavour', 'NCC-71805', 'Part of the tachyon blockade during the Klingon Civil War.[6] Participates at the Battle of Sector 001.[2]'),
('Nebula class','USS Farragut', 'NCC-60597', 'Helps recover Enterprise-D crew at Veridian III. Destroyed in the Lembatta Cluster by Klingons.[120]'),
('Nebula class','USS Hera', 'NCC-62006', 'Disappeared while under the command of Captain Silva La Forge with a mostly Vulcan crew of 300.[121]'),
('Nebula class','USS Honshū', 'NCC-60205', 'Destroyed while transporting Gul Dukat to stand trial.[122]'),
('Nebula class','USS Leeds', 'NCC-70352', 'Participates in the Battle for Deep Space 9.[85]'),
('Nebula class','USS Lexington', 'NCC-61832', 'Participates in the Battle of Sector 001.[2]'),
('Nebula class','USS Merrimack', 'NCC-61827', 'Transported Sarek from Legara IV to Vulcan.[123]'),
('Nebula class','USS Monitor', 'NCC-61826', 'Sent to the Romulan Neutral Zone in anticipation of a possible Romulan attack.[124]'),
('Nebula class','USS Nebula', 'NX-60147', 'Presumable namesake ship for the class.'),
('Nebula class','USS Phoenix', 'NCC-65420', 'Carries out unauthorized attacks on Cardassian ships while under the command of Captain Benjamin Maxwell.[125] Not specified whether she''s named for the mythological bird, the American city, or humanity''s first FTL-capable spacecraft.'),
('Nebula class','USS Prometheus', 'NCC-71201', 'Used by Dr. Gideon Seyetik in his project to reignite a dead star.[126]'),
('Nebula class','USS Proxima', 'NCC-61952', 'Missing in the Gamma Quadrant.[108]'),
('Nebula class','USS Ranger', 'NX-31472-B', 'Lost during the Borg Invasion of 2381, the vessel was defending the planet Khitomer.[127]'),
('Nebula class','USS Sutherland', 'NCC-72015', 'Briefly commanded by Lieutenant Commander Data while part of the tachyon blockade during the Klingon Civil War.[6]'),
('Nebula class','USS T''Kumbra', 'NCC-62100', 'All-Vulcan crew challenges the Deep Space Nine crew to a game of baseball. Participated in the Dominion War.[128]'),
('Nebula class','USS Ulysses', 'NCC-66808', 'Studied protoplanetary masses in the Helaspont Nebula.[129]'),
('Nebula class','USS Nightingale', 'NCC-60805', 'Minor starship in Star Trek: Bridge Commander. Used as a search-and-rescue vessel. Fate uncertain.'),
('Nebula class','USS Khitomer', 'NCC-66613', 'Minor starship in Star Trek: Bridge Commander. Lead a failed assault on Alioth 6. Fate uncertain.'),
('Nebula class','USS Berkeley', 'NCC-64720', 'Minor starship in Star Trek: Bridge Commander. Originally sent to study the Vesuvi Dust Cloud but failed due to the intense radiation of the dust cloud. Attacked by a Kessok probe but survived. Fate uncertain.'),
-- ('New Orleans class',),
-- ('Named for the City of New Orleans. Designated as frigates.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('New Orleans class','USS Kyushu', 'NCC-65491', 'Destroyed at the Battle of Wolf 359.[21]'),
('New Orleans class','USS Renegade[1]', 'NCC-63102', 'Rendezvoused with the Enterprise-D over Dytallix B, where Captain Tryla Scott met with Jean-Luc Picard to discuss an alien conspiracy to take over Starfleet.[11]'),
('New Orleans class','USS Rutledge[1]', 'NCC-57295', 'Ship aboard which Miles O''Brien[130] and Benjamin Maxwell served during the Cardassian War.[125] Participated in the counterattack against the Klingons in the Archanis sector.[120]'),
('New Orleans class','USS Thomas Paine[1]', 'NCC-65530', 'Rendezvoused with the Enterprise-D over Dytallix B, where Captain Rixx met with Jean-Luc Picard to discuss an alien conspiracy to take over Starfleet.[11] Part of the tachyon blockade during the Klingon Civil War.[6]'),
-- ('Niagara class',),
-- ('Name', 'Registry', 'Depiction'),
('Niagara class','USS Princeton', 'NCC-59804', 'Destroyed at the Battle of Wolf 359.[21]'),
('Niagara class','USS Wellington', 'NCC-28473', 'Ship aboard which Ro Laren served, and where she was posted before being court-martialed.[131] Underwent a computer system upgrade by Bynar technicians at Starbase 74.[113]'),
-- ('Nimitz class',),
-- ('Named for World War II Fleet Admiral Chester W. Nimitz'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Nimitz class','USS Europa', 'NCC-1648', 'Commanded by Admiral Brett Anderson. Destroyed by a cloaked Klingon ship during the Battle at the Binary Stars.'),
-- ('Norway class',),
-- ('Name', 'Registry', 'Depiction'),
('Norway class','USS Budapest', 'NCC-64923', 'Participates in the Battle of Sector 001.[2]'),
('Norway class','USS Norway', 'NX-62341, to NCC-62341', 'Presumable namesake ship for the class.'),
-- ('Nova class',),
-- ('Name', 'Registry', 'Depiction'),
('Nova class','USS Equinox', 'NCC-72381', 'Stranded in the Delta Quadrant.[132] Heavily damaged by USS Voyager and destroyed by self-destruct initiated by Captain Rudolph Ransom.[132]'),
('Nova class','USS Everett', 'NCC-72392', 'Commanded by Captain Claudia Alisov. Attached to the Department of Temporal Investigations. Appears in the Department of Temporal Investigations novels.'),
('Nova class','USS Lionheart', 'NCC-73808', 'Medical vessel temporarily commanded by Christine Vale in the novel Star Trek: The Fall - The Poisoned Chalice.'),
('Nova class','USS Twilight', 'NCC-74413', 'Starfleet Intelligence attached science vessel temporarily commanded by Jaryd Harker, MD in the novel Star Trek: Adamant.'),
('Nova class','USS Nova', 'NX-73515', 'Presumable namesake ship for the class.'),
('Nova class','USS Rhode Island', 'NCC-72701', 'Commanded by Captain Harry Kim in an alternate future.[133]'),
-- ('NX class',),
-- ('Ships are named for the NASA Space Shuttle orbiters.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('NX class','Enterprise', 'NX-01', 'Lead ship. Captained by Jonathan Archer. Primary setting for Star Trek: Enterprise. Launched in 2151. Decommissioned in 2161.'),
('NX class','Columbia', 'NX-02', 'Commanded by Captain Erika Hernandez.[134] Launched in 2154 and participated in the Klingon–Augment crisis. After an uncertain term of service, it was eventually lost but was later discovered intact on a desert planet in the Gamma Quadrant. Fate of crew unknown.[134]'),
('NX class','Challenger', 'NX-03', 'Mentioned in the Star Trek: Enterprise novel The Romulan War: Beneath the Raptor''s Wing.'),
('NX class','Discovery', 'NX-04', 'Mentioned in the Star Trek: Enterprise novel The Romulan War: Beneath the Raptor''s Wing.'),
('NX class','Atlantis', 'NX-05', 'Mentioned in the Star Trek: Enterprise novel The Romulan War: Beneath the Raptor''s Wing.'),
('NX class','Endeavour', 'NX-06', 'Mentioned in the Star Trek: Enterprise novels The Romulan War: Beneath the Raptor''s Wing and The Romulan War: To Brave the Storm. Later entered Federation Starfleet service and rebuilt into Columbia class.'),
('NX class','Intrepid', 'NX-07', 'Commanded by Jason Lambert. Mentioned in the Star Trek: The Next Generation novel Indistinguishable from Magic.'),
('NX class','ISS Enterprise', 'NX-01', 'The Mirror Universe counterpart of the Enterprise (NX-01).[135]'),
('NX class','ISS Avenger', 'NX-09', 'In the Mirror Universe, an Imperial Starfleet warship.[135]'),
('NX class','USS Franklin', 'NX-326', 'The ship was commanded by Captain Balthazar Edison and vanished during a mission in the Gagarin Radiation Belt, an incident later taught to future Starfleet officers at Starfleet Academy. The Franklin is a 22nd-century United Earth starship and is the first Starfleet vessel capable of Warp 4. It was built about a century before Captain James T. Kirk''s USS Enterprise and is equipped with earlier versions of the later ship''s technologies.'),
-- ('Oberth class',),
-- ('Named after the rocket scientist Hermann Oberth.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Oberth class','USS Banting (simulation ship)', 'NCC-639', 'Simulated Oberth class vessel used by Academy trainees in Star Trek: Starfleet Academy.'),
('Oberth class','USS Biko', 'NCC-50331', 'Rendezvoused with the USS Enterprise-D at Deinonychus VII.[136]'),
('Oberth class','USS Bonestell', 'NCC-31600', 'Destroyed in the Battle of Wolf 359.[12]'),
('Oberth class','USS Cochrane', 'NCC-59318', 'Ferries Admiral Norah Satie to the Enterprise-D.[137] and Julian Bashir and Lieutenant Jadzia Dax to Deep Space Nine.[12]'),
('Oberth class','USS Copernicus', 'NCC-640', 'Berthed at spacedock.[51]'),
('Oberth class','USS Grissom', 'NCC-638', 'Transports David Marcus and Lieutenant Saavik to the Genesis planet.[43] Destroyed by Klingons.[43] Named for NASA astronaut Virgil I. "Gus" Grissom who died during preparations and testing for the Apollo One mission. Commanded by Captain J. T. Esteban.'),
('Oberth class','USS LaGrange', 'NCC-617', 'Transports negotiators in the game Star Trek: Starfleet Academy. This ship is destroyed by the simulator.'),
('Oberth class','USS Oberth', 'NCC-602', 'First ship of the class. Assigned to deep space exploration in 2293, when "Operation Retrieve" was proposed.[50]'),
('Oberth class','USS Pegasus', 'NCC-53847', 'Equipped with an illegal prototype cloaking device that malfunctions, causing the ship to become embedded inside an asteroid.[75]'),
('Oberth class','USS Raman', 'NCC-29487', 'Lost while investigating gas giant planet Marijne VII.[121]'),
('Oberth class','SS Tsiolkovsky', 'NCC-53911', 'Crew infected by the Psi 2000 virus. Destroyed in asteroid collision.[138]'),
('Oberth class','USS Valiant', 'NCC-20000', 'Helps recover Enterprise-D crew at Veridian III.[77]'),
('Oberth class','USS Yosemite', 'NCC-19002', 'Studied the plasma arc between binary stars.[139][140]'),
('Oberth class','SS Vico', 'NAR-18834', 'Research vessel that was in service with Starfleet in the mid-24th century. Vico operated out of Starbase 514. In 2368, the Vico explored an astronomical formation known as a black cluster. Found derelict by Enterprise-D.[141]'),
-- ('Odyssey class',),
-- ('Introduced in Star Trek Online.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Odyssey class','USS Enterprise', 'NCC-1701-F', 'Commanded by Captain Va''kel Shon. Participated in the second battle for Deep Space Nine as well as the final battle against the Iconians in Star Trek: Online.[citation needed]'),
('Odyssey class','USS Houston', 'NCC 97284', 'The Houston, commanded by Admiral D''Vak, lead the federation in an assault against the Borg Queen''s Octahedron in the space around the Unicomplex.[citation needed]'),
('Odyssey class','USS Odyssey', 'NX-97000', 'First ship of the Odyssey-class. Commissioned at Utopia Planetia. Currently in service.[citation needed]'),
('Odyssey class','USS Yorktown', 'NCC-97005', 'The Yorktown fought at the Battle of Sol in the Iconian war, and was nearly destroyed. It was later found by Starfleet and refitted into the Yorktown subclass of the Odyssey class starships.[citation needed]'),
('Odyssey class','USS Hamilton', 'NCC-97014', 'The Hamilton fought in many skirmishes along the Klingon border during the Third Klingon And Federation War. She later fought in the second battle of DS9 alongside ships like the USS Enterprise. The Hamilton was a major component during the Iconian War. She was later destroyed in a Hur’q attack at DS9.[citation needed]'),
('Odyssey class','USS Kent', 'NCC-97165', 'The Kent was a ship of exploration in the early 25th Century. She later went missing during the Iconian War. Two years after she went missing, a fragment of her hull was found adrift in the Ba''aja Sector. The rest of the ship was later found in the Boreth Sector in 2429.[citation needed]'),
('Odyssey class','USS Victory', 'NCC-98003', 'The Victory was the Last Odyssey class starship to be built. She was launched in late 2419 and would be used as an exploration vessel. She was named after the battleship HMS Victory.[citation needed]'),
-- ('Olympic class',),
-- ('This class is sometimes erroneously named "Hope class" from an early version of the dedication plaque from the USS Pasteur.[1]'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Olympic class','USS Olympic', 'NCC-54905', 'Presumable namesake ship for the class. The namesake for this vessel is most likely the ocean liner RMS Olympic.'),
('Olympic class','USS Nobel', 'NCC-55012', 'Visited Deep Space Three to search for the missing USS Hera.[121] Served in the Dominion War.[38]'),
('Olympic class','USS Pasteur', 'NCC-58925', 'Ship commanded by Beverly Picard in an alternate timeline.[94] Destroyed by warp core breach in the Devron system.[94] Featured in the episode "All Good Things...".'),
-- ('Prometheus class',),
-- ('Name', 'Registry', 'Depiction'),
('Prometheus class','USS Prometheus', 'NX-59650', '(later NX-74913) First class starship; still under development; captured by Romulans and recovered by Starfleet personnel after the EMH from USS Voyager and the EMH Mark II incapacitated the Romulan crew.[119]'),
-- ('Renaissance class',),
-- ('Name', 'Registry', 'Depiction'),
('Renaissance class','USS Aries', 'NCC-45167', 'Ship offered to William Riker to command.[142] Part of the tachyon blockade during the Klingon Civil War.[6]'),
('Renaissance class','USS Hornet', 'NCC-45231', 'Part of the tachyon blockade during the Klingon Civil War.[6] Named for the World War II aircraft carrier.[1] Participates in the Dominion War.[105]'),
('Renaissance class','USS Maryland', 'NCC-45109', 'Missing in the Gamma Quadrant.[108]'),
('Renaissance class','USS Renaissance', 'NCC-40521', 'Presumable namesake ship for the class.'),
-- ('Rigel class',),
-- ('Named for the star Rigel.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Rigel class','USS Akagi', 'NCC-62158', 'Part of the tachyon blockade during the Klingon Civil War.[6] Served in the Dominion War.[38] Named for HIJMS Akagi.[1]'),
('Rigel class','USS Rigel', 'NCC-62000', 'Presumable namesake ship for the class.'),
('Rigel class','USS Tolstoy', 'NCC-62095', 'Destroyed in the Battle of Wolf 359.[21]'),
-- ('Saber class',),
-- ('Name', 'Registry', 'Depiction'),
('Saber class','USS da Vinci', 'NCC-81623', 'Lead ship in Starfleet Corps of Engineers novel series. Named for Leonardo da Vinci.'),
('Saber class','USS Endurance', 'NCC-70114', 'Mentioned as replacement ship for Captain Christine McDonald in the book Star Trek: Preserver.'),
('Saber class','USS Falchion', 'Unknown', 'Featured in the novel Star Trek: The Fall – A Ceremony of Losses.'),
('Saber class','USS Marco Polo', 'Unknown', 'Commanded by Deanna Troi during the Gateways crisis in the novel Star Trek: The Next Generation – Gateways: Doors Into Chaos.'),
('Saber class','USS Musgrave', 'Unknown', 'Featured in the novel Star Trek – A Singular Destiny.'),
('Saber class','USS Saber', 'NCC-79221', 'Presumable namesake ship for the class.'),
('Saber class','USS Yeager', 'NCC-61947', 'Participates in the Battle of Sector 001.[2]'),
-- ('Sequoia class',),
-- ('Name', 'Registry', 'Depiction'),
('Sequoia class','USS Sequoia', 'NCC-70070', 'Presumable namesake ship for the class.'),
('Sequoia class','USS Yellowstone', 'NCC-70073', 'Transports Ensign Melora Pazlar to Deep Space Nine in 2370.[143]'),
-- ('Shepard class',),
-- ('Named for American astronaut Alan Shepard who became the first American to travel into space.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Shepard class','USS Gagarin', 'NCC-1309', 'Ambushed and destroyed by the Klingons.'),
('Shepard class','USS Kerala', 'NCC-1255', 'Destroyed at the Battle at the Binary Stars.'),
('Shepard class','USS Ride', 'NCC-1265', 'Fought at the Battle at the Binary Stars.'),
-- ('Sovereign class',),
-- ('Name', 'Registry', 'Depiction'),
('Sovereign class','USS Atlas', 'NCC-82745', 'Commanded by Morgan Bateson in the 2380s.'),
('Sovereign class','USS Bozeman', 'NCC-1941-A', 'Successor to the first Bozeman. Participated in the Battle of Sector 001.[144]'),
('Sovereign class','USS Enterprise', 'NCC-1701-E', 'Primary setting for Star Trek: First Contact, Star Trek: Insurrection, Star Trek Nemesis and also made an appearance on Bridge Commander. Commanded by Captain Jean-Luc Picard.'),
('Sovereign class','USS First Minister', 'Unknown', 'Mentioned in the novel Star Trek: Typhon Pact – Plagues of Night.'),
('Sovereign class','USS Gibraltar', 'NCC-75689', 'Sacrificed itself against the Borg in 2381 in Star Trek: Destiny.'),
('Sovereign class','USS Kongo', 'NCC-97891', 'The Dominion wars with Starfleet took a heavy toll in the 2370''s,and then after the Klingon and Iconian wars Starfleet put in to active Service the ( Sovereign-Archon Class Starships. ) The USS Kongo was Commissioned on stardate:94354.6 in the year 2416. The Plaque reads as follows ("Never give up, Never Surrender").'),
('Sovereign class','USS President', 'Unknown', 'Mentioned in the novel Star Trek: Typhon Pact – Plagues of Night.'),
('Sovereign class','USS Sovereign', 'NX-73811 - NCC-73811', 'First ship of the class which acts as a pathfinder ship. Appears in Star Trek Bridge Commander. Also features in the Shatnerverse novel Spectre.'),
('Sovereign class','USS Sentinel', 'NCC-17331', 'Appears in Star Trek: Invasion. Also mentioned in the great transaction for graviton stabilizers.[32]'),
('Sovereign class','USS Tempest', 'Unknown', 'Participates in the Borg Invasion of 2381 in Star Trek: Destiny.'),
('Sovereign class','USS Valiant', 'NCC-75418', 'The Defiant class starship, USS Valiant NCC-74210 was destroyed in the year 2374 by the Jem''Hadar after a failed attempt to destroy a new Dominion Battleship class vessel. The new Valiant was put into active service just one year later as a Sovereign class starship.'),
('Sovereign class','USS Warspite', 'Unknown', 'Appears in the novel Star Trek: The Fall – A Ceremony of Losses.'),
-- ('Soyuz class',),
-- ('Named for the Soviet spacecraft'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Soyuz class','USS Bozeman', 'NCC-1941', 'Spends several decades caught in a temporal causality loop; Commanded by Captain Morgan Bateson (Kelsey Grammer). Named for Bozeman, Montana, launching place of humanity''s first warp ship[145] and hometown of Brannon Braga, the writer of the episode the ship appeared in. The registration number was a reference to the 1979 film 1941 due to modelmaker Greg Jein working on both projects.[146]'),
('Soyuz class','USS Soyuz', 'NCC-1939', 'Presumable namesake ship for the class.'),
-- ('Springfield class',),
-- ('Name', 'Registry', 'Depiction'),
('Springfield class','USS Chekov', 'NCC-57302', 'Destroyed in the Battle of Wolf 359.[21]'),
('Springfield class','USS Springfield', 'NCC-53500', 'Presumable namesake ship for the class.'),
-- ('Freedom class (Kelvin timeline)',),
-- ('Name', 'Registry', 'Depiction'),
('Freedom class','USS Franklin', 'NX-326', '(Kelvin timeline) Former United Earth Military Assault Command Operations ship relaunched in the 2160s shortly after the formation of the United Federation of Planets under the command of Balthazar Edison. One of the first ships capable of achieving Warp 4. Lost in the Gagarin Radiation Belt. Recovered by James T. Kirk and the survivors of USS Enterprise in 2263 and returned to Starbase Yorktown to stop Krall.[45]'),
-- ('Steamrunner class',),
-- ('Name', 'Registry', 'Depiction'),
('Steamrunner class','USS Appalachia', 'NCC-52136', 'Participates in the Battle of Sector 001.[2]'),
('Steamrunner class','USS Steamrunner', 'NX-76220 to NCC-76220', 'Presumable namesake ship for the class.'),
-- ('Surak class',),
-- ('Named for Vulcan philosopher Surak.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Surak class','USS Surak', 'NCC-65601', 'Presumable namesake ship for the class.'),
('Surak class','USS Zapata', 'NCC-33184', 'Scheduled to rendezvous with the Enterprise-D.[22] Fought in the Dominion War.[38]'),
-- ('Sydney class',),
-- ('Name', 'Registry', 'Depiction'),
('Sydney class','USS Jenolan', 'NCC-2010', 'Crashed on the surface of a Dyson sphere while transporting Captain Montgomery Scott to a retirement colony. Montgomery Scott stored himself in the transporters of this starship. Destroyed.[147]'),
('Sydney class','USS Nash', 'NCC-20105', 'Transports personnel to and from Deep Space Nine.[148]'),
('Sydney class','USS Sydney', 'NCC-2005', 'Presumable namesake ship for the class.'),
-- ('Theophrastus class',),
-- ('Name', 'Registry', 'Depiction'),
('Theophrastus class','USS Demeter', 'NCC-79914', 'Commanded by Liam O''Donnell. Part of "Project Full Circle" in the Star Trek: Voyager relaunch novels.'),
('Theophrastus class','USS Theophrastus', 'Unknown', 'Presumable namesake ship for the class, and possibly named after the Swiss chemist Philippus Aureolus Theophrastus Bombastus von Hohenheim, also known as Paracelsus.'),
-- ('Universe class',),
-- ('Name', 'Registry', 'Depiction'),
('Universe class','USS Enterprise', 'NCC-1701-J', 'Participates in a decisive battle against the Sphere Builders in the 26th century.[149] Reference image page 244 The Star Trek Encyclopedia[1] for class identification (2016 edition).'),
-- ('Vesta class',),
-- ('Introduced in Star Trek: Destiny and first visualized in Star Trek Online.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Vesta class','USS Aventine', 'NCC-82602', 'First command of Captain Ezri Dax in Star Trek: Destiny. Has prototype slipstream warp drive.'),
('Vesta class','USS Capitoline', 'NCC-82617', 'Attached to the Department of Temporal Investigations. Mentioned in the Department of Temporal Investigations novels.'),
('Vesta class','USS Esquiline', 'NCC-82614', 'Commanded by Captain Parimon Dasht. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle. Destroyed by the Omega Continuum in 2381 in The Eternal Tide.'),
('Vesta class','USS Quirinal', 'NCC-82610', 'Commanded by Captain Regina Farkas. Part of "Project Full Circle" in the Star Trek: Voyager novel Full Circle. Destroyed by the Omega Continuum in 2381 in The Eternal Tide.'),
('Vesta class','USS Vesta', 'NCC-82601', 'Commanded by Captain Regina Farkas. Lead ship of the Vesta class. Mothballed soon after launch due to technical issues. Relaunched and becomes part of "Project Full Circle" in 2381 in the Star Trek: Voyager novel Protectors.'),
-- ('Walker class',),
-- ('The class was named for NASA test pilot Joe Walker.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Walker class','USS Shenzhou', 'NCC-1227', 'Commanded by Captain Philippa Georgiou. First Officer was Lieutenant Commander Michael Burnham. As a result of the Battle of the Binary Stars in 2256, the crew evacuated the ship, leaving it abandoned.'),
('Walker class','USS Walker', 'NCC-1226', 'Presumable namesake ship for the class.'),
-- ('Wambundu class',),
-- ('Name', 'Registry', 'Depiction'),
('Wambundu class','USS Drake', 'NCC-20381', 'Command offered to William Riker, but given to Paul Rice.[150] Ordered to investigate the Lorenze Cluster, where it is destroyed by a Minosian Echo Papa 607 weapons platform.[150]'),
('Wambundu class','USS Fleming', 'NCC-20316', 'Disabled and later destroyed at the Hekaras Corridor.[151]'),
('Wambundu class','USS Wambundu', 'NCC-20300', 'Presumable namesake ship for the class.'),
-- ('Wells class',),
-- ('Named in honor of science fiction author H. G. Wells.'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Wells class','USS Pastak', 'NCV-474438-G', 'Timeship that saves the character from a Tholian attack in Star Trek Online.'),
('Wells class','USS Relativity', 'NCV-474439-G', 'Timeship Relativity, from the 29th century, ship designed to transport people through time, set on a mission to prevent the destruction of the USS Voyager.[81]'),
('Wells class','USS Wells', 'NGV-474438-A', 'Presumable namesake ship for the class.'),
-- ('Yorkshire class',),
-- ('Name', 'Registry', 'Depiction'),
('Yorkshire class','USS Denver', 'NCC-54927', 'Destroyed while transporting 517 colonists to the Beloti Sector.[152]'),
('Yorkshire class','USS Yorkshire', 'NCC-54900', 'Presumable namesake ship for the class.'),
-- ('Zodiac class',),
-- ('[citation needed]'),
-- (''),
-- ('Name', 'Registry', 'Depiction'),
('Zodiac class','USS Yorktown', 'NCC-61137', 'Ordered to make long-range sensor sweeps of the Devron system in an alternate reality.[94]'),
('Zodiac class','USS Zodiac', 'NCC-61000', 'Presumable namesake ship for the class.'),
-- ('Undetermined class',),
-- ('Name', 'Registry', 'Depiction'),
('Undetermined class','Phoenix', 'unknown', 'Earth spaceship used in the 21st century. It was the first Earth-made, manned spacecraft to achieve light speed using warp drive. It was practically a "junk-bucket, mounted on top of an atomic war missile". The Phoenix is remembered as the ship that instigated Earth''s first contact with Vulcans. Featured in Star Trek: First Contact and flown by Dr. Zefram Cochrane, Commander William Riker, and Lt. Commander Geordi La Forge.'),
('Undetermined class','U.F.P.F. Challenger', 'OV91951L', 'Commander Nick Keller. Featured in Star Trek - New Earth: Challenger and Star Trek: Challenger – Gateways: Chainmail. Built out of the USS Peleliu and named for space shuttle Challenger.'),
('Undetermined class','USS Carolina', 'Unknown', 'Ship ordered by Admiral Paris to intercept Gegis'' ship after he stole Barclay''s hologram.[153]'),
('Undetermined class','SS Conestoga', 'Pre Starfleet', 'Ship that carried colonists to the "lost colony" of Terra Nova.[154]'),
('Undetermined class','USS Curry', 'NCC-42254.', 'Pathfinder ship for the Curry class, another "kitbash" model.[155]'),
('Undetermined class','USS Excalibur', 'Unknown', 'Marika Willkarah mentions this ship at the Borg crash site to Seven of Nine and other Borg crash survivors.[156]'),
('Undetermined class','USS Gallico', 'Unknown', 'Mentioned in an arrival log on DS9 from Starbase 58 under Captain J. Priestly.[157]'),
('Undetermined class','USS G''Mat', 'Unknown', 'Mentioned in an arrival log on DS9 from System C-171 under Captain M. Bligh.[157]'),
('Undetermined class','USS Hispanola', 'Unknown', 'Mentioned in an arrival log on DS9 under Captain J. Gump.[157]'),
('Undetermined class','USS Narbonne', 'Unknown', 'Colony support vessel mentioned in the Star Trek: Discovery novel "Drastic Measures". Captained by Aurobindo Korrapati.'),
('Undetermined class','USS Olympia', 'Unknown', 'Crashed on an L-class planet during an exploration of the mission to the Beta Quadrant. Captained by Lisa Cusack.[158]'),
('Undetermined class','Starfleet Cruiser Peleliu', 'Unknown', 'Captain Roger Lake. From Star Trek: New Earth – Challenger. Named for the Battle of Peleliu. Severely damaged and reconstructed into the UFPF Challenger.'),
('Undetermined class','USS Raven', 'NAR-32450', 'Science and exploration vessel used by the Hansens for exploration of the Delta Quadrant where Seven of Nine was assimilated by the Borg.[159]'),
('Undetermined class','USS Tombaugh', 'Unknown', 'Mentioned by Seven of Nine in a log under personality of Ensign Stone. Under the command of Captain Blackwood. Assimilated by the Borg.[160]'),
('Undetermined class','USS Veracruz', 'Unknown', 'Brings relief troops to AR-558.[161]'),
('Undetermined class','USS Yorktown', 'Unknown', 'Woman referring to herself as Cmdr. Bloom meets Cmdr. Riker at Tilonius Institute for Mental Disorders.[140] Mentioned in an arrival log on DS9.[157]'),
('Undetermined class','Timeship Aeon', 'Unknown', 'Piloted by Captain Braxton, attempts to destroy USS Voyager but instead throws it back to 1996.[162]'),
('Undetermined class','USS Destiny', 'NCC-74791', 'Ezri Tigan''s prior assignment before transferring to Deep Space Nine.[163]'),
-- ('Non-starships and support vessels'),
-- ('Danube class runabout',),
-- ('Main article: Runabout (Star Trek)'),
-- ('Name', 'Registry', 'Depiction'),
('Danube class runabout','USS Danube', 'NX-72003', 'First ship of the class. Mentioned in Star Trek: Deep Space Nine Technical Manual.'),
('Danube class runabout','USS Gander', 'NCC-73624', 'Taken by Ezri Dax to search for Worf.[164] Destroyed by the Jem''Hadar.[164]'),
('Danube class runabout','USS Ganges', 'NCC-72454', 'Captured Tahna Los.[165] Rescued Vash from the Gamma Quadrant.[166] Destroyed by a T''Lani Munitions Cruiser.[167]'),
('Danube class runabout','USS Mekong', 'NCC-72617', 'Helps rescue Benjamin Sisko from the Jem''Hadar.[99] Destroyed by the Jem''Hadar during the Obsidian Order/Tal Shiar attack on the Founders'' homeworld in the Omarian Nebula.[29]'),
('Danube class runabout','USS Orinoco', 'NCC-72905', 'Helps rescue Benjamin Sisko from the Jem''Hadar.[99] Destroyed by the Cardassian terrorist group "The True Way".[168]'),
('Danube class runabout','USS Rio Grande', 'NCC-72452', 'Vessel aboard which Jadzia Dax and Benjamin Sisko discover the Bajoran wormhole.[12] Later located the missing Sword of Kahless. Helps rescue Sisko from the Jem''Hadar.[99] Longest surviving DS9 runabout.[original research?]'),
('Danube class runabout','USS Rubicon', 'NCC-72936', 'Shrunk to 6.5 centimeters.[169]'),
('Danube class runabout','USS Shenandoah', 'NCC-73024', 'Taken by Dax and Worf to rescue a Cardassian informant from the Dominion.[170] Severely damaged by the Jem''Hadar en route to deliver diplomatic message to Grand Nagus Zek.[65]'),
('Danube class runabout','USS Volga', 'NCC-73196', 'Participates in botanical survey of Torad IV.[171]'),
('Danube class runabout','USS Yangtzee Kiang', 'NCC-72453', 'Hijacked by Bajoran terrorist Tahna Los.[165] Became the first DS9 runabout to be destroyed when it crashed on a moon in the Gamma Quadrant.[172]'),
('Danube class runabout','USS Yolja', 'NCC-75353', 'First runabout to be named after a non-Earth river. Assigned to Deep Space 9. Appeared in Worlds of Star Trek: Deep Space Nine, Volume Three – The Dominion: Olympus Descending.'),
('Danube class runabout','USS Yukon', 'NCC-74602', 'Stolen by Founder in failed attempt to destroy the Bajoran sun. Destroyed by a Protomatter Device also killing a Founder.[173]'),
-- ('Peregrine class fighter',),
-- ('Name', 'Registry', 'Depiction'),
('Peregrine class fighter','Flurnoy', 'unknown', 'Used by the Maquis.[174] Participated in the Dominion War.[85]'),
-- ('Yellowstone class runabout',),
-- ('Main article: Runabout (Star Trek)'),
-- ('Name', 'Registry', 'Depiction'),
('Yellowstone class runabout','USS Yellowstone', 'NX-74751', 'Prototype for an advanced runabout designed in large part by Ensign Harry Kim and Lieutenant Laska in an alternate timeline.[7] Destroyed by antimatter containment loss.[7]'),
-- ('Shuttlecraft',),
-- ('Main article: Shuttlecraft (Star Trek)'),
-- ('Name', 'Mothership', 'Depiction'),
('Shuttlecraft','Aeroshuttle', 'unknown', 'Upgraded shuttlecraft attached to Intrepid-class starships.[175]'),
('Shuttlecraft','Calypso', 'USS Enterprise-D', 'Captain''s yacht.[176]'),
('Shuttlecraft','Columbus', 'USS Enterprise', 'Shuttle NCC-1701/2, dispatched to search the planet Taurus II from orbit for the shuttlecraft Galileo.[177]'),
('Shuttlecraft','Copernicus', 'USS Enterprise-A', 'Shuttle NCC-1701-A/3, used to transport Kirk, Spock, McCoy, and Sybok to the planet "Eden".[178]'),
('Shuttlecraft','Cousteau', 'USS Enterprise-E', 'Captain''s yacht.[179]'),
('Shuttlecraft','Curie', 'USS Enterprise-D', 'Shuttle taken by Worf to the Bat''leth tournament.[20][180]'),
('Shuttlecraft','Dawkins', 'unknown', 'Shuttlecraft on which Reginald Barclay arrives on Jupiter Station.[181]'),
('Shuttlecraft','Delta Flyer', 'USS Voyager', 'Advanced shuttlecraft. First one destroyed.[182] Second built.[183]'),
('Shuttlecraft','Einstein', 'USS Enterprise-D', 'Shuttle 02 that carries Captain Picard and Wesley Crusher to Starbase 515.[184]'),
('Shuttlecraft','El-Baz', 'USS Enterprise-D', 'Shuttle 05 carrying Captain Picard from the future.[185]'),
('Shuttlecraft','Fermi', 'USS Enterprise-D', 'Suffers a transporter accident.[186]'),
('Shuttlecraft','Galileo', 'USS Enterprise', 'Shuttle NCC-1701/7 (named after Galileo Galilei), which burned up in the atmosphere over the planet Taurus II.[177]'),
('Shuttlecraft','second Galileo', 'USS Enterprise', 'Second shuttle with the identification NCC-1701/7, used to ferry Ambassador Sarek and his wife Amanda (Mr. Spock''s parents) to the USS Enterprise,[187][188][189] temporarily disabled while being used to transport Commissioner Hedford, Spock, Kirk, and Dr. McCoy to the USS Enterprise after being hijacked by an energy field (the "Companion"),[190][191] and used by Spock to examine a large, energy-draining space creature.[192][193]'),
('Shuttlecraft','Galileo II', 'USS Enterprise', 'Third shuttle with the identification NCC-1701/7, temporarily stolen by Dr. Sevrin and his followers to visit the planet "Eden".[194][195]'),
('Shuttlecraft','new Galileo', 'USS Enterprise-A', 'Shuttle NCC-1701-A/5, used for transport to/from Nimbus III; severely-damaged during manual shipboard landing.[178]'),
('Shuttlecraft','Gilliam', 'unknown', 'Shuttle that takes Dr. McCoy and Kirk to the Enterprise.[44]'),
('Shuttlecraft','Goddard', 'USS Enterprise-D', 'Shuttle given to Captain Scott on an "extended loan".[147]'),
('Shuttlecraft','Hawking', 'USS Enterprise-D', 'Shuttle piloted by Commander Riker carrying Ambassador Odan.[196]'),
('Shuttlecraft','Jumpship', 'unknown', 'A small atmospheric shuttlecraft that could be operated by a single pilot. Jumpships were used by Starfleet as emergency evacuation craft in the late 2250s of the alternate reality.'),
('Shuttlecraft','Justman', 'USS Enterprise-D', 'Testbed for Dr. Rega''s Metaphasic Shield.[197] Named for Star Trek production executive Robert Justman.'),
('Shuttlecraft','Magellan', 'USS Enterprise-D', 'Shuttle piloted by Commander Riker researching "null space".[198]'),
('Shuttlecraft','Onizuka', 'USS Enterprise-D', 'Shuttle used by Geordi La Forge to go to Risa when he was kidnapped by the Romulans.[199] Named after astronaut Ellison Onizuka.'),
('Shuttlecraft','Picasso', 'Starbase 11', 'Shuttle SB11-1201/1, in which Kirk chased the USS Enterprise while on its way to the forbidden planet Talos IV.[200][201]'),
('Shuttlecraft','Pike', 'USS Enterprise-D', 'Unnumbered shuttlecraft used by Data to transport hitridium. Destroyed.[82]'),
('Shuttlecraft','Sakharov', 'USS Enterprise-D', 'Shuttlecraft 01 used for an experiment with the genetically engineered children.[92]'),
('Shuttlecraft','SC-4', 'unknown', 'Armored shuttle taking Admiral Janeway to the past.[202]'),
('Shuttlecraft','Waverider', 'USS Equinox', 'Upgraded atmospheric shuttle.[132]'),
('Shuttlecraft','Shuttlecraft Cochrane', 'USS Voyager', 'Testbed for Warp 10 flight piloted by Tom Paris.[203] Closely resembles the later hull design for Delta Flyer. Destroyed attempting to retrieve warp core.[204]'),
('Shuttlecraft','Einstein', 'USS Enterprise', 'Shuttle NCC-1701/6, destroyed after Commodore Decker stole it and made a kamikaze run against an alien planet killer.[205][206]'),
('Shuttlecraft','Canterbury', 'USS Hamilton', 'Destroyed when the Hamilton rammed into a Borg Cube in "fluidic space".[citation needed]')

